dist: focal
language: python
python:
- 3.9
install:
- pip install -r requirements.txt
- pip install .
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: andrewrothstein
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: aveCGIkBvdGOl5Zvs66VaPchPgSDOZ6vt168ipgB9t4Xjy9VixmTYJgE0NOapYkRIi8QD6aNiBBV95wdiq3sCjN8JcUdNO/sMpbss5OtbjuwJPamlb7fe0/u+BzsH8237cWJeJeTIghDf2CygJ70TtemlMwOJHIuYYx/KBU7Kf1yHoSdgSEmzzRqjCqTSAdQmCQ3MEJly5eA6ORf1pWo0WX/4wNjpvHybCeTi9857Kfo0K0jpdSOWI/uF1DYeaoNPHs5e3MrE9QZMfHcBh6q9tVIbNNnfWnoG/um0Hw461yTcOLxnyIf8MQM4BpFryAS4KbVWi0GO0IG6NuBoN5QH/4i9+U7+IkDeES/uwkiOebBmCvryiZDlZvgzGse6LfkovKF2v0ctSCPXazlY8U9HqvxlWmYmE8V0erySpvu9EqA29XHsk4WTmYAIT7W9X1jW9GhAiwrcKfDwFyDqjIJAteH0SwU1Wbb7HMEZCY1nW32AxYc/Vu0T0uJQgUWvohgnTUqqO67tfb8AtNdeJQV4Y9/kSieNdbZhyW3PB1neizVhnXTp5/tftioJA80RQFq9ay7PY+dW/q94dXe20+7BrG4ja4pq8sBf5nhtx/mbwCpAj5iyqht7qQPflOH7ycr4MhmKYhX6SgE7GlTwFrqdHQ3LCb+eXxYQi3zxt3Zh0M=
